# Generated by Django 4.2.3 on 2023-07-18 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_created_post_draft_post_modified_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 7, 18, 3, 7, 15, 82774, tzinfo=datetime.timezone.utc), upload_to='media/post/'),
            preserve_default=False,
        ),
    ]
